---
- name: 批量全自动卸载清理
  hosts: all
  gather_facts: no
  tasks:
    - name: 1. 停止并禁用 Xray 服务
      systemd:
        name: xray
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: 2. 删除 Xray 相关文件
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/xray
        - /usr/local/etc/xray
        - /usr/local/share/xray
        - /etc/systemd/system/xray.service
        - /etc/systemd/system/xray@.service
        - /etc/systemd/system/xray.service.d
        - /tmp/install.sh
        - /tmp/xray.zip

    - name: 3. 卸载 Nginx 并清理网页
      shell: |
        apt-get purge -y nginx nginx-common
        apt-get autoremove -y
        rm -rf /var/www/html/index.html
        rm -rf /etc/nginx
      ignore_errors: yes

    - name: 4. 重载系统服务
      systemd:
        daemon_reload: yes

    - name: 5. 清理本地结果记录
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ./temp_links
        - ./final_nodes.txt
